### ISSUE TITLE
File not found和userRateLimitExceeded问题

### ISSUE THREAD

**Issue by fzsimlu** [iwestlin/gd-utils#163]
问题1

创建目录重试中： 霍比特人 重试次数： 6
创建目录重试中： 霍比特人 重试次数： 7
{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 0APMoVXhw0Vd7Uk9PV.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 0APMoVXhw0Vd7Uk9PV."}}
复制失败 15UuiEYzn8ySDZfK5N5H9qNRGY3 --> 0APMoVXhw0Vd7Uk9PV
Error: Request failed with status code 404 目录名：霍比特人
    at create_folder (/gd-utils/src/gd.js:404:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

这2天使用莫名出现这个错误，不确定是否因为gd-utils缓存导致还是。
猜想
1.假设别人分享中的文件中午霍比特人目录，应该不会出现复制此文件夹或文件情况。
2.复制到自己的网盘又会自己创建文件，所以不确定问题出哪里。

问题2
环境：出现超额之后，新增100个SA账号，开始另外一个新的任务
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
这个超额提示本不应该提示
原因1，我在复制之前，是新创建了100个SA账号，按照网上说法1个账号750G，100个好几T流量，我搬运只有200G左右，不应该超。
猜想
是否因为此前存在搬运未完成的，当我新增100个SA账号之后，自动开始之前的搬运。所以当我开始新的搬运，导致超额？

**Comment by iwestlin** [comment]
`File not found: 0APMoVXhw0Vd7Uk9PV`
这里应该是你团队盘ID打错了，最后少了一个`A`

关于 `userRateLimitExceeded` 请看 https://github.com/iwestlin/gd-utils/blob/master/changelog.md

**Comment by iwestlin** [comment]
源ID也不对，应该是 `15UuiEYzn8ySDZfK5N5H9qNRGY3xpmhNi`
为什么会输错。。

**Comment by fzsimlu** [comment]
> `File not found: 0APMoVXhw0Vd7Uk9PV`
> 这里应该是你团队盘ID打错了，最后少了一个`A`
> 
> 关于 `userRateLimitExceeded` 请看 https://github.com/iwestlin/gd-utils/blob/master/changelog.md

{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 0APMoVXhw0Vd7Uk9PVA.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 0APMoVXhw0Vd7Uk9PVA."}}
{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 0APMoVXhw0Vd7Uk9PVA.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 0APMoVXhw0Vd7Uk9PVA."}}
创建目录重试中： 霍比特人 重试次数： 6
创建目录重试中： 霍比特人 重试次数： 7
是对的，原本日志

**Comment by iwestlin** [comment]
那应该就是sa没有权限

命令行运行 `./validate-sa.js 0APMoVXhw0Vd7Uk9PVA` 检查下sa的权限

**Comment by fzsimlu** [comment]
因为添加的json有点多，只有部分没前线，大部分都有。只有一些没有权限，就或中断吗？必须都有权限的情况下，才不会出现这个错误吗？

**Comment by iwestlin** [comment]
每次请求有7次重试的机会，每次都会随机选一个sa，如果大部分有权限按理是不会连续7次报404的

你执行的命令是什么，最后有没有加 `-S`？如果没加，会默认用到个人帐号的授权

**Comment by fzsimlu** [comment]
> 每次请求有7次重试的机会，每次都会随机选一个sa，如果大部分有权限按理是不会连续7次报404的
> 
> 你执行的命令是什么，最后有没有加 `-S`？如果没加，会默认用到个人帐号的授权

是用tg dokcer版本，直接用机器人的复制命令，如要要加这个-S ,能通过配置默认加上吗，因为不是手输命令行

**Comment by iwestlin** [comment]
机器人默认是用sa授权的，不需要加

**Comment by fzsimlu** [comment]
更新最新版本。还是存在。 
环境：团队考到自己edu盘，SA有部分没权限，edu盘的问题？
getaddrinfo ENOTFOUND www.googleapis.com
复制文件失败，文件id: 16yTwWTJduWWtfUcP0p2v6YxWqDPhMSqa
{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 1Ybt-cyBJKJQ0rLYlEHLqS4UlrxpOKq1b.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 1Ybt-cyBJKJQ0rLYlEHLqS4UlrxpOKq1b."}}
getaddrinfo ENOTFOUND www.googleapis.com
