### ISSUE TITLE
bot突然没反应了

### ISSUE THREAD

**Issue by Drrickkk** [iwestlin/gd-utils#187]
我刚点击开始复制后bot就没反应了，重启了VPS后也是一样
我开始复制之前还是有反应的
https://i.loli.net/2020/08/25/KpjswAubgi9RDqd.png

**Comment by Drrickkk** [comment]
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2020-08-25T14:47:55: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-08-25T14:47:55: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-08-25T14:47:55: PM2 log: App [server:0] online
PM2        | 2020-08-25T14:47:57: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-08-25T14:47:57: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-08-25T14:47:57: PM2 log: App [server:0] online
PM2        | 2020-08-25T14:47:58: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-08-25T14:47:58: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-08-25T14:47:58: PM2 log: App [server:0] online
PM2        | 2020-08-25T14:48:00: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-08-25T14:48:00: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-08-25T14:48:00: PM2 log: App [server:0] online
PM2        | 2020-08-25T14:48:04: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-08-25T14:48:04: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-08-25T14:48:04: PM2 log: App [server:0] online

/root/.pm2/logs/server-out.log last 15 lines:
0|server   |               "callback_data": "update 1SGpm4rVSmEIGgzkaj8k8H2KUOjDF7FHG"
0|server   |             },
0|server   |             {
0|server   |               "text": "清除按钮",
0|server   |               "callback_data": "clear_button"
0|server   |             }
0|server   |           ]
0|server   |         ]
0|server   |       }
0|server   |     },
0|server   |     "chat_instance": "-2966959495243960786",
0|server   |     "data": "copy 1SGpm4rVSmEIGgzkaj8k8H2KUOjDF7FHG"
0|server   |   }
0|server   | }
0|server   | 1 'task interrupted'

/root/.pm2/logs/server-error.log last 15 lines:
0|server   |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|server   |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|server   |     at require (internal/modules/cjs/helpers.js:25:18)
0|server   |     at Object.<anonymous> (/root/gd-utils/src/router.js:5:264)
0|server   | TypeError: Cannot destructure property `tg_token` of 'undefined' or 'null'.
0|server   |     at Object.<anonymous> (/root/gd-utils/src/tg.js:9:22)
0|server   |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|server   |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|server   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|server   |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|server   |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|server   |     at require (internal/modules/cjs/helpers.js:25:18)
0|server   |     at Object.<anonymous> (/root/gd-utils/src/router.js:5:264)
PM2       | App [server:0] exited with code [1] via signal [SIGINT]
PM2       | App [server:0] starting in -fork mode-
PM2       | App [server:0] online
0|server  | TypeError: Cannot destructure property `tg_token` of 'undefined' or 'null'.
0|server  |     at Object.<anonymous> (/root/gd-utils/src/tg.js:9:22)
0|server  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|server  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|server  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|server  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|server  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|server  |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|server  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|server  |     at require (internal/modules/cjs/helpers.js:25:18)
0|server  |     at Object.<anonymous> (/root/gd-utils/src/router.js:5:264)
PM2       | App [server:0] exited with code [1] via signal [SIGINT]
PM2       | App [server:0] starting in -fork mode-
PM2       | App [server:0] online

**Comment by iwestlin** [comment]
> Cannot destructure property tg_token of 'undefined' or 'null'.

看上去是你的 `config.js` 配置出问题了。
是这样配置的吗：
https://github.com/iwestlin/gd-utils/blob/3f61a643fd1ce4cada46967e5e396fef8b596f3f/config.js#L14

**Comment by iwestlin** [comment]
另外开始大量文件的任务时，程序需要一段时间从数据库读取所有文件数据，这会导致进程阻塞，造成机器人不响应，等一等就好了

**Comment by Drrickkk** [comment]
> 
> 
> > Cannot destructure property tg_token of 'undefined' or 'null'.
> 
> 看上去是你的 `config.js` 配置出问题了。
> 是这样配置的吗：
> 
> https://github.com/iwestlin/gd-utils/blob/3f61a643fd1ce4cada46967e5e396fef8b596f3f/config.js#L14

是的，应该是这样的，第二天就有回应了就是延迟有点高，感谢大佬
