### ISSUE TITLE
无域名版本bot总是提示重启，内贴pm2 logs

### ISSUE THREAD

**Issue by yysm** [iwestlin/gd-utils#205]
0|index    | socket hang up
0|index    | [bot.error.event] TypeError: clear_button is not a function
0|index    |     at Object.bot.on.msg (/root/gd-utils/index.js:285:23)
0|index    |     at promises.push.Promise (/root/gd-utils/node_modules/telebot/lib/telebot.js:484:29)
0|index    |     at new Promise (<anonymous>)
0|index    |     at TeleBot.event (/root/gd-utils/node_modules/telebot/lib/telebot.js:477:32)
0|index    |     at TeleBot.callback_query (/root/gd-utils/node_modules/telebot/lib/updates.js:135:21)
0|index    |     at TeleBot.processUpdate (/root/gd-utils/node_modules/telebot/lib/telebot.js:67:55)
0|index    |     at promise.then (/root/gd-utils/node_modules/telebot/lib/telebot.js:326:51)
0|index    |     at process._tickCallback (internal/process/next_tick.js:68:7)

/root/.pm2/logs/index-out.log last 15 lines:
0|index    | [bot.plugin] loaded 'regExpMessage' plugin
0|index    | [bot.plugin] loaded 'shortReply' plugin
0|index    | [bot.plugin] loaded 'namedButtons' plugin
0|index    | [bot.plugin] loaded 'regExpMessage' plugin
0|index    | [bot.plugin] loaded 'shortReply' plugin
0|index    | [bot.plugin] loaded 'namedButtons' plugin
0|index    | [bot.info] bot started
0|index    | [bot.plugin] loaded 'regExpMessage' plugin
0|index    | [bot.plugin] loaded 'shortReply' plugin
0|index    | [bot.plugin] loaded 'namedButtons' plugin
0|index    | [bot.info] bot started
0|index    | [bot.plugin] loaded 'regExpMessage' plugin
0|index    | [bot.plugin] loaded 'shortReply' plugin
0|index    | [bot.plugin] loaded 'namedButtons' plugin
0|index    | [bot.info] bot started

PM2      | pm2 has been killed by signal, dumping process list before exit...
PM2      | Deleting process 0
PM2      | Stopping app:index id:0
PM2      | App [index:0] exited with code [0] via signal [SIGTERM]
PM2      | pid=56298 msg=process killed
PM2      | Exited peacefully
0|index  | [bot.plugin] loaded 'regExpMessage' plugin
0|index  | [bot.plugin] loaded 'shortReply' plugin
0|index  | [bot.plugin] loaded 'namedButtons' plugin
0|index  | [bot.info] bot started
PM2      | pm2 has been killed by signal, dumping process list before exit...
PM2      | Deleting process 0
PM2      | Stopping app:index id:0
PM2      | App [index:0] exited with code [0] via signal [SIGTERM]
PM2      | pid=58657 msg=process killed
PM2      | Exited peacefully
0|index  | [bot.plugin] loaded 'regExpMessage' plugin
0|index  | [bot.plugin] loaded 'shortReply' plugin
0|index  | [bot.plugin] loaded 'namedButtons' plugin
0|index  | [bot.info] bot started

之后就每分钟循环一次

**Comment by yysm** [comment]
这个问题是出现在安装完成后重启出现的。

**Comment by iwestlin** [comment]
可能是依赖的原因
参见 https://github.com/iwestlin/gd-utils/issues/190#issuecomment-683240877

**Comment by yysm** [comment]
可以给一下详细修改说明吗？没这方面经验，小白一个。谢谢。

**Comment by yysm** [comment]
> 可能是依赖的原因
> 认为[＃190（评论）](https://github.com/iwestlin/gd-utils/issues/190#issuecomment-683240877)

可以给一下详细修改说明吗？没这方面经验，小白一个。谢谢。
