### ISSUE TITLE
有没有新的方法获取sa，AutoRclone现在获取sa会报错了

### ISSUE THREAD

**Issue by christan-duplicate** [iwestlin/gd-utils#212]
有没有新的方法获取sa，AutoRclone现在获取sa会报错了

**Comment by dmuxue** [comment]
尽量使用未删除过的项目,就不会报错

新的谷歌id

**Comment by Dingzhenpiyi** [comment]
我也是创建SA失败，请问有解决办法吗？

**Comment by Mrycp** [comment]
我也是创建SA失败，404报错，接口直接请求不到，查看接口里提示：The request is missing a valid API key
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/saf-giatwp59nehqekew-xfyrjiigu/serviceAccounts?pageSize=100&alt=json returned "Requested entity was not found.">

**Comment by lzkgbld** [comment]
我这边运行是报错
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 323, in <module>
    download_keys=args.download_keys
  File "gen_sa_accounts.py", line 168, in serviceaccountfactory
    creds.refresh(Request())
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('deleted_client: The OAuth client was deleted.', '{\n  "error": "deleted_client",\n  "error_description": "The OAuth client was deleted."\n}')

**Comment by LMY0312** [comment]
我卡在这了，已经快要结束了，给我来个报错
Traceback (most recent call last):
  File "D:\AutoRclone\gen_sa_accounts.py", line 311, in <module>
    resp = serviceaccountfactory(
  File "D:\AutoRclone\gen_sa_accounts.py", line 173, in serviceaccountfactory
    creds = flow.run_console()
  File "D:\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 414, in run_console
    self.fetch_token(code=code)
  File "D:\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 288, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests_oauthlib\oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "D:\Python\Python39\lib\site-packages\requests_oauthlib\oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 182, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 47, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

**Comment by zacred0rryn** [comment]
> 我这边运行是报错 Traceback (most recent call last): File "gen_sa_accounts.py", line 323, in download_keys=args.download_keys File "gen_sa_accounts.py", line 168, in serviceaccountfactory creds.refresh(Request()) File "/usr/local/lib/python3.7/dist-packages/google/oauth2/credentials.py", line 206, in refresh self._scopes, File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 248, in refresh_grant response_data = _token_endpoint_request(request, token_uri, body) File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request _handle_error_response(response_body) File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response raise exceptions.RefreshError(error_details, response_body) google.auth.exceptions.RefreshError: ('deleted_client: The OAuth client was deleted.', '{\n "error": "deleted_client",\n "error_description": "The OAuth client was deleted."\n}')

我报的和这个几乎一模一样的错，不知道该怎么解决。
