### ISSUE TITLE
check.js没问题，但是copy报错

### ISSUE THREAD

**Issue by TomatoFryEggs** [iwestlin/gd-utils#24]
报错如下：
```
复制文件夹出错 ErrorWithCode: private_key and client_email are required.
    at GoogleToken.getCredentials (/home/Jobin/gd-utils/node_modules/gtoken/build/src/index.js:94:27)
    at async GoogleToken.getTokenAsync (/home/Jobin/gd-utils/node_modules/gtoken/build/src/index.js:128:27) {
  code: 'MISSING_CREDENTIALS'
}
```

**Comment by TomatoFryEggs** [comment]
sa没弄好
