### ISSUE TITLE
pm2 log 报错

### ISSUE THREAD

**Issue by TomatoFryEggs** [iwestlin/gd-utils#57]
```
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:58:20: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:58:21: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:58:22: PM2 log: App [server:0] exited with code [1] via signal [SIGINT]
PM2        | 2020-07-03T21:58:22: PM2 log: Script /home/Jobin/gd-utils/server.js had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/server-out.log last 15 lines:
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333

/root/.pm2/logs/server-error.log last 15 lines:
0|server   |   syscall: 'listen',
0|server   |   address: '0.0.0.0',
0|server   |   port: 23333
0|server   | }
0|server   | Error: listen EADDRINUSE: address already in use 0.0.0.0:23333
0|server   |     at Server.setupListenHandle [as _listen2] (net.js:1313:16)
0|server   |     at listenInCluster (net.js:1361:12)
0|server   |     at doListen (net.js:1498:7)
0|server   |     at processTicksAndRejections (internal/process/task_queues.js:85:21) {
0|server   |   code: 'EADDRINUSE',
0|server   |   errno: 'EADDRINUSE',
```

**Comment by iwestlin** [comment]
已经有程序监听了23333端口，是不是启动了两次server？

`pm2 ls` 看看守护了那些进程

`pm2 delete 进程ID` 可以删掉某个进程

**Comment by TomatoFryEggs** [comment]
删了好了，但是又出现80端口permission denied
```
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/Jobin/.pm2/pm2.log last 15 lines:
PM2        | 2020-07-03T21:57:11: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:57:12: PM2 log: App [server:0] online
PM2        | 2020-07-03T21:57:26: PM2 log: App [server:0] exited with code [0] via signal [SIGTERM]
PM2        | 2020-07-03T21:57:26: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-03T21:57:26: PM2 log: App [server:0] online
PM2        | 2020-07-04T09:02:16: PM2 log: Stopping app:server id:0
PM2        | 2020-07-04T09:02:16: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-07-04T09:02:17: PM2 log: pid=6053 msg=process killed
PM2        | 2020-07-04T09:03:17: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-04T09:03:17: PM2 log: App [server:0] online
PM2        | 2020-07-04T09:07:00: PM2 log: Stopping app:server id:0
PM2        | 2020-07-04T09:07:00: PM2 log: App [server:0] exited with code [0] via signal [SIGINT]
PM2        | 2020-07-04T09:07:00: PM2 log: pid=15002 msg=process killed
PM2        | 2020-07-04T09:07:09: PM2 log: App [server:0] starting in -fork mode-
PM2        | 2020-07-04T09:07:09: PM2 log: App [server:0] online

/home/Jobin/.pm2/logs/server-error.log last 15 lines:
0|server   |   syscall: 'listen',
0|server   |   address: '0.0.0.0',
0|server   |   port: 80
0|server   | }
0|server   | Error: listen EACCES: permission denied 0.0.0.0:80
0|server   |     at Server.setupListenHandle [as _listen2] (net.js:1296:21)
0|server   |     at listenInCluster (net.js:1361:12)
0|server   |     at doListen (net.js:1498:7)
0|server   |     at processTicksAndRejections (internal/process/task_queues.js:85:21) {
0|server   |   code: 'EACCES',
0|server   |   errno: 'EACCES',
0|server   |   syscall: 'listen',
0|server   |   address: '0.0.0.0',
0|server   |   port: 80
0|server   | }

/home/Jobin/.pm2/logs/server-out.log last 15 lines:
0|server   | http://127.0.0.1:80
0|server   | http://127.0.0.1:80
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333
0|server   | http://127.0.0.1:23333

```

**Comment by iwestlin** [comment]
你手动把port改成80了吗，netstat -tulpen 看看哪个程序占用了80端口

**Comment by TomatoFryEggs** [comment]
```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:25500           0.0.0.0:*               LISTEN      0          17149      -
tcp        0      0 0.0.0.0:23333           0.0.0.0:*               LISTEN      1004       15090872   15465/node /home/Jo
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          15015039   -
tcp        0      0 127.0.0.1:45265         0.0.0.0:*               LISTEN      1004       3972343    10175/node
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      102        14940      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          6679599    -
tcp6       0      0 :::22                   :::*                    LISTEN      0          6679610    -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           0          16948      -
udp        0      0 127.0.0.53:53           0.0.0.0:*                           102        14939      -
udp        0      0 10.140.0.5:68           0.0.0.0:*                           101        15075980   -
udp6       0      0 ::1:323                 :::*                                0          16949      -
```

**Comment by TomatoFryEggs** [comment]
> 你手动把port改成80了吗，netstat -tulpen 看看哪个程序占用了80端口

之前改了，后来又改回来了。

**Comment by iwestlin** [comment]
项目文件修改后需要 pm2 reload server 生效的

我提供下思路，你自己排查下吧。

先 pm2 ls 看看有没有正常启动server

然后 curl 127.0.0.1:你设置的端口号 ，默认23333那个

然后检查下 nginx的配置，有没有吧 80端口的流量转发到你设置的端口

nginx -t 是检查配置语法

nginx -s reload 是让配置生效

然后 curl 127.0.0.1 看看是不是返回 not found，是的话说明nginx成功把流量从80转到你设置的端口了

最后在cloduflare上添加一条解析到你的服务器上，记得钩上 proxy，然后cloudflare的 ssl/tls设置里确保加密模式为灵活，这样cloudflare就能把https的流量转发到你的80端口上来了

最后 curl https://你设置的域名，如果返回 not found 就说明配好了

最后 curl -F "url=[YOUR_WEBSITE]/api/gdurl/tgbot" 'https://api.telegram.org/bot[YOUR_BOT_TOKEN]/setWebhook'

把你的网址和tg机器人绑定。

如果返回 webhook was set，说明绑定成功，去服务器打开 pm2 logs看实时日志，给机器人发个消息，正常的话你会看到tg发过来的请求信息。

**Comment by TomatoFryEggs** [comment]
> 项目文件修改后需要 pm2 reload server 生效的
> 
> 我提供下思路，你自己排查下吧。
> 
> 先 pm2 ls 看看有没有正常启动server
> 
> 然后 curl 127.0.0.1:你设置的端口号 ，默认23333那个
> 
> 然后检查下 nginx的配置，有没有吧 80端口的流量转发到你设置的端口
> 
> nginx -t 是检查配置语法
> 
> nginx -s reload 是让配置生效
> 
> 然后 curl 127.0.0.1 看看是不是返回 not found，是的话说明nginx成功把流量从80转到你设置的端口了
> 
> 最后在cloduflare上添加一条解析到你的服务器上，记得钩上 proxy，然后cloudflare的 ssl/tls设置里确保加密模式为灵活，这样cloudflare就能把https的流量转发到你的80端口上来了
> 
> 最后 curl [https://你设置的域名，如果返回](https://%E4%BD%A0%E8%AE%BE%E7%BD%AE%E7%9A%84%E5%9F%9F%E5%90%8D%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%BF%94%E5%9B%9E) not found 就说明配好了
> 
> 最后 curl -F "url=[YOUR_WEBSITE]/api/gdurl/tgbot" '[https://api.telegram.org/bot[YOUR_BOT_TOKEN]/setWebhook](https://api.telegram.org/bot%5BYOUR_BOT_TOKEN%5D/setWebhook)'
> 
> 把你的网址和tg机器人绑定。
> 
> 如果返回 webhook was set，说明绑定成功，去服务器打开 pm2 logs看实时日志，给机器人发个消息，正常的话你会看到tg发过来的请求信息。

非常感谢！
原因让人很失望，我配置的没问题，是我原来用阿里的dns去解析的，换成cloudflare就好了。
