### ISSUE TITLE
關於telegram bot的SA

### ISSUE THREAD

**Issue by SachiaLanlus** [iwestlin/gd-utils#59]
因為用量沒有大到需要用SA
所以在原先local端就沒有設定SA
然而部屬到telegram bot之後
似乎預設是使用SA
導致無法使用
想請問如何設定讓telegram bot不要用SA呢
感謝您

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/src/tg.js
把上面这个文件中的
`service_account: true`
全部改成 `service_account: false`
应该就可以了

不过那样的话以后如果我也修改了这个文件，你再更新代码就要处理合并冲突了。

我过段时间在配置里加个参数好了，你不急的话可以等等

**Comment by SachiaLanlus** [comment]
太感謝了
剛才改完可以用了
話說大佬不睡的嗎？
10分鐘內...

**Comment by SachiaLanlus** [comment]
不好意思
昨天只測了copy
更改完`service_account: false`copy確認是可以用的
但是count還是會有SA的問題
具體錯誤如下
```
0|server  | Error: 没有可用的SA帐号
0|server  |     at get_sa_token (/home/ubuntu/gd-utils/src/gd.js:303:9)
0|server  |     at gen_headers (/home/ubuntu/gd-utils/src/gd.js:263:40)
0|server  |     at ls_folder (/home/ubuntu/gd-utils/src/gd.js:232:25)
0|server  |     at /home/ubuntu/gd-utils/src/gd.js:182:35
0|server  |     at /home/ubuntu/gd-utils/node_modules/p-try/index.js:4:10
0|server  |     at new Promise (<anonymous>)
0|server  |     at pTry (/home/ubuntu/gd-utils/node_modules/p-try/index.js:3:37)
0|server  |     at run (/home/ubuntu/gd-utils/node_modules/p-limit/index.js:24:18)
0|server  |     at /home/ubuntu/gd-utils/node_modules/p-limit/index.js:46:18
0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|server  | 信息获取完毕
0|server  | 所有目录读取完毕
0|server  | Error: 没有可用的SA帐号
0|server  |     at get_sa_token (/home/ubuntu/gd-utils/src/gd.js:303:9)
0|server  |     at gen_headers (/home/ubuntu/gd-utils/src/gd.js:263:40)
0|server  |     at ls_folder (/home/ubuntu/gd-utils/src/gd.js:232:25)
0|server  |     at /home/ubuntu/gd-utils/src/gd.js:182:35
0|server  |     at /home/ubuntu/gd-utils/node_modules/p-try/index.js:4:10
0|server  |     at new Promise (<anonymous>)
0|server  |     at pTry (/home/ubuntu/gd-utils/node_modules/p-try/index.js:3:37)
0|server  |     at run (/home/ubuntu/gd-utils/node_modules/p-limit/index.js:24:18)
0|server  |     at /home/ubuntu/gd-utils/node_modules/p-limit/index.js:46:18
0|server  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|server  | 信息获取完毕
0|server  | 所有目录读取完毕
```

**Comment by iwestlin** [comment]
好 我刚解决了最头疼的问题，现在来搞这个

**Comment by iwestlin** [comment]
<img width="369" alt="截屏2020-07-04 下午4 12 33" src="https://user-images.githubusercontent.com/6235509/86508428-9a8f6900-be12-11ea-8e40-8254239783e8.png">

刚更新的代码加上了这个功能。我自己试了下没问题。
需要在config里自己设置一个 `USE_PERSONAL_AUTH`，如图，然后把它加到 module.exports = {
USE_PERSONAL_AUTH,
后面不变，这样机器人就会使用个人的授权信息进行操作了

另外注意的是因为目前只支持单个的个人授权，不像sa那样可以多个同时调用。
所以有可能会触发Google的api频率调用限制，如果遇到这种情况的话建议 `PARALLEL_LIMIT` 调小一点

**Comment by SachiaLanlus** [comment]
剛才拿了幾個新的連結測試完後
應該是沒問題了
感謝您
